version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5433:5432  # expose postgres port to be able to access it from the host machine, but use 5433 to avoid collisions

  py:
    image: python:3.6 # cannot install py_stringmatching in 3.7 with pip https://github.com/anhaidgroup/py_stringmatching/issues/53
    tty: true # allocate a TTY do not exit immediately
    ports:
      - 5000:5000

    depends_on:
      - db
    volumes:
      - ../:/src # bind all source folders to the /src-directory in the container
    environment:
      - DB_CONNECTION=dbname='admin' user='admin' host='db' port=5432 password='admin'
